name: Generator Stats Profile 2D

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta automáticamente todas las noches
  workflow_dispatch: # Activa el botón para ejecutarlo manualmente cuando quieras

# ESTO ES LO QUE FALTA: Permite al script guardar archivos en tu repositorio
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Generar la tarjeta de Estadísticas Generales en formato SVG
      - uses: marcalexiei/github-readme-stats-action@v2.0.1
        with:
          card: stats
          options: 'username=Lu2077&show_icons=true&include_all_commits=true&count_private=true&theme=dracula'
          path: stats.svg

      # 2. Generar la tarjeta de Lenguajes más usados en formato SVG
      - uses: marcalexiei/github-readme-stats-action@v2.0.1
        with:
          card: top-langs
          options: 'username=Lu2077&layout=compact&langs_count=7&theme=dracula'
          path: languages.svg

      # 3. Guardar físicamente las imágenes generadas dentro de tu repositorio principal
      - name: Commit & Push cambios de forma segura
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update local profile statistics SVGs"
          file_pattern: 'stats.svg languages.svg'

