name: GitHub Profile Stats Generator

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta automáticamente todas las noches
  workflow_dispatch: # Activa el botón para ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Generar gráfico plano de Estadísticas Generales con tema Dracula
      - uses: marcalexiei/github-readme-stats-action@v0.1.2
        with:
          username: Lu2077
          output: stats.svg
          include_all_commits: true
          count_private: true
          show_icons: true
          theme: dracula

      # 2. Generar gráfico plano de Lenguajes más usados en formato compacto
      - uses: marcalexiei/github-readme-stats-action@v0.1.2
        with:
          username: Lu2077
          output: languages.svg
          layout: compact
          langs_count: 7
          theme: dracula

      # 3. Guardar físicamente las imágenes generadas dentro de tu repositorio (Evita el 404)
      - name: Commit & Push cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg languages.svg
          git commit -m "Update local profile statistics SVGs" || exit 0
          git push origin main




