name: GitHub Profile Stats Generator

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta automáticamente todas las noches
  workflow_dispatch: # Activa el botón para ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Generar la tarjeta de Estadísticas Generales en formato SVG
      - uses: marcalexiei/github-readme-stats-action@v2.0.1
        with:
          card: stats
          options: 'username=Lu2077&show_icons=true&include_all_commits=true&count_private=true&theme=dracula'
          path: stats.svg

      # 2. Generar la tarjeta de Lenguajes más usados en formato SVG
      - uses: marcalexiei/github-readme-stats-action@v2.0.1
        with:
          card: top-langs
          options: 'username=Lu2077&layout=compact&langs_count=7&theme=dracula'
          path: languages.svg

      # 3. Guardar físicamente las imágenes generadas dentro de tu repositorio principal
      - name: Commit & Push cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg languages.svg
          git commit -m "Update local profile statistics SVGs" || exit 0
          git push origin main




