name: Generator Stats Profile 2D

on:
  schedule:
    - cron: "0 0 * * *" # Corre automáticamente todas las noches
  workflow_dispatch: # Te permite ejecutarlo manualmente con un botón

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # 1. Generar la tarjeta de Estadísticas Generales en PNG
      - name: Generar Estadísticas de Perfil
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: stats.png                # Cambiado a .png
          config_output: png                 # Fuerza el formato PNG
          base: header, activity, community, repositories, metadata
          config_timezone: America/Santiago
          config_theme: dracula

      # 2. Generar la tarjeta de Lenguajes Más Usados en PNG
      - name: Generar Lenguajes más Usados
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: languages.png            # Cambiado a .png
          config_output: png                 # Fuerza el formato PNG
          base: header                       # Activamos cabecera para asegurar estabilidad
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_ignored: html, css
          plugin_languages_limit: 7
          config_timezone: America/Santiago
          config_theme: dracula




